version: "3"

services:
  web:
    command: npm start
    image: node
    ports:
      - "1111:1111"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    environment:
      PORT: 1111

  db: 
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=11
      - POSTGRES_USER=hodempsey
      - POSTGRES_DB=ratings